---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

author_note: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
mask              : no

class             : "man"
output            : papaja::apa6_pdf

header-include:
    - \DeclareDelayedFloatFlavor{foo}{table}
---

```{r load_packages, include = FALSE}
library("papaja")
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants


```{r}

table1 <- tibble(first=rep(letters,3),
                 second = rnorm(78,10,2))


kable(table1, "latex", align = "l", booktabs = T, linesep="", caption = "A very long table", longtable=T) %>% 
  column_spec(1, width = "5em", bold = F, italic = F) %>%
  kable_styling(font_size = 7) %>% 
  column_spec(2, width = "8em", bold = F, italic = F) %>% 
  kable_styling(latex_options = "repeat_header")
```

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup